---

ansible_python_interpreter: "/usr/bin/python3"
timezone: "UTC"

# list of admin users:
admins:
  robo:
    username: "robo"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1qbkiSDrsFMoka/OScoFySsP+YzDYkATMsITL4zg6pR/lmDsRyVfWF7dNeZEXKOHU2+AtBy3FP70WqBl1NlApRZa28fFzfkVXmrXXTAi0JRnjiV3BgCvq4JFs+aWrj2WccjV8UXEIVywDqi3jrzd+d9oQEStfx6ClboByjpc+gPuu8qnDzXpi7Q5GfJnwN8gK9wn3vj2WgJDnniBG58g8yiXRacMgOya8ZhbseCow0wmjHMg4MYot8iAmuwkGqiqCMg5AUgmKcEwFrphD4EUfl8iQZYvxsfR46ccVL6IG/To/oCYxVFSxKGH/AdaKsoMXmKDBE9N3Mxuqso8ZsDuUdqnzWpOVRbZo5GDyGinb0j6Muikyw8JYfZ6TbVhzEX3lxy1Jkb6kEmqF0VMLGHWXQiIn/tHEjhj3/2EMIZcEtl1OZ2TcAvR6sYCFgRFQWyD2J17gkUwuxe7V0ZOstLOXJ51aoL6JJCfWKi1vecpq9Ye0N8G2mPSYkAhQRlHGKj7BiKcWdVBoiZRh1ylhoP9ecc5UPMpIIgq9oAzZQMa0zVOzvQWlI96Q0vXpn5ogQHHkD95aquDaF79zG4VPyd/slUmdSc+CVq0WXjh25X1PqZM45/XyO9noDerKE6BdlsE3I2NZo9FJ4rGnYBF1lGYTrpHyugZjaTHRQrgX63DYow== robo@robo.home.rhawks.net"
