---

ansible_python_interpreter: "/usr/bin/python3"
timezone: "UTC"

allowed_ports:
  - "80"
  - "443"
  - "25565"
  - "8080"
limited_ports:
  - "22"
# list of admin users:
admins:
  robo:
    username: "robo"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDT7gLDr9P1oScCzZZJrw0BtTNe9+jRxjrt8WlDxUWY8HFTSQZ91yx6u1twvPcuvOUCchtcXKO+3QMEZg18KS17i5kEmNvtXu29w2jMYrK1dVwiYrBRKjBXG/fjmcmIg//6+Madp0f8IcStp+XDsGBFoc4RTcpBHF8k1BHDi0BDhBghfNDqT5NyoPpTb7B9iNq2MvoAgduwNtiL22hlYCawjB1OS6i3qgZQBA6xx8TierzBmxt7Z9ZtOCFUlmhVnOXC+uto9UVMkXuCzNfBo/Ca/SDqYOHU1NQPP9zgub5Zhzg3LcEGtqN9mPUgwTxiZGln5AdZtCjB0kmGkOCa+EH1ru8kDxPt18F+O4r62aez9tmIEtzQxQ0b2fRA1L1x2Wr8mAUX1I9udX89Tbt2tp1qui/ax69d9e9INRcbsomYpFTsdmWh/KlQMcbzUHgQyilpxRbQoRznwvxNVOUo+tFOmNDmIh8UWBsDUQ6hjVCNeKdGgAgvQBaeYVgpw9F5m2k= robo@robo.home.rhawks.net"
  tyler:
    username: "tyler"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYkOlx6Of+cKHdb396lb2qnWU8v2+M++pPOGyjsWnWxb6ZhKMKo633y/n7g0Hh6Vz9lAlOJ86tlX5NKl8ovNyk6riP323f0KuXTFUxwROfeHSgTjjFDXIExBhltHigGv/RyxvyqSxUex68e4hfaxRuU/mvUdc4ZMUI8AH/P4umIIXJAoceX9kGHCkvy3NilJJwOanQr0DAjDkueAIntsERfPEwnYL4IAlaCO77dP+gnw1PMFDBUFoBEJBRp5gFbs6LKGRAsTMfnSHOX8E3dAdZwmI8enPRqgp+8fV8WW7gFmqfOn0DGRSpiSYShGOQkB400/MgrNRprJKqRiLj8SVf rsa-key-20230415"
vhosts:
  admin.terrashift.net:
    php_fpm: "php8.1"
    doc_root: "public/"
  grafana.terrashift.net:
    proxy:
      port: 3000
  map.terrashift.net:
    proxy:
      port: 8100
      ip: "{{ hostvars['host.terrashift.net']['ansible_enp6s0'].ipv4.address }}"
  stats.terrashift.net: {}
  apply.terrashift.net:
    proxy:
      port: 4000
  locations.terrashift.net:
    proxy:
      port: 4001
  cms.terrashift.net:
    proxy:
      port: 5176
