---
ansible_python_interpreter: "/usr/bin/python3"
timezone: "UTC"

# list of admin users:
admins:
  robo:
    username: "robo"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1qbkiSDrsFMoka/OScoFySsP+YzDYkATMsITL4zg6pR/lmDsRyVfWF7dNeZEXKOHU2+AtBy3FP70WqBl1NlApRZa28fFzfkVXmrXXTAi0JRnjiV3BgCvq4JFs+aWrj2WccjV8UXEIVywDqi3jrzd+d9oQEStfx6ClboByjpc+gPuu8qnDzXpi7Q5GfJnwN8gK9wn3vj2WgJDnniBG58g8yiXRacMgOya8ZhbseCow0wmjHMg4MYot8iAmuwkGqiqCMg5AUgmKcEwFrphD4EUfl8iQZYvxsfR46ccVL6IG/To/oCYxVFSxKGH/AdaKsoMXmKDBE9N3Mxuqso8ZsDuUdqnzWpOVRbZo5GDyGinb0j6Muikyw8JYfZ6TbVhzEX3lxy1Jkb6kEmqF0VMLGHWXQiIn/tHEjhj3/2EMIZcEtl1OZ2TcAvR6sYCFgRFQWyD2J17gkUwuxe7V0ZOstLOXJ51aoL6JJCfWKi1vecpq9Ye0N8G2mPSYkAhQRlHGKj7BiKcWdVBoiZRh1ylhoP9ecc5UPMpIIgq9oAzZQMa0zVOzvQWlI96Q0vXpn5ogQHHkD95aquDaF79zG4VPyd/slUmdSc+CVq0WXjh25X1PqZM45/XyO9noDerKE6BdlsE3I2NZo9FJ4rGnYBF1lGYTrpHyugZjaTHRQrgX63DYow== robo@robo.home.rhawks.net"
  temc_oof:
    username: "temc_oof"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkDl+HzX2giX6gNDoap4JSbPPW3fYFpkDjxapv4Qx/N3qGNqnWhNWEfD2UbE19N1d9nu/rYin6Y2mPGrxEttXWAX6QzEqR8M3arO22jG2m4Tr4BitkenQt00ASUNo0jgou9oTIukqaFRA85ITZN6zti9Qo8sQpNZwXfrwvSY5cDvtzGRqVWkoyJ/HtHTiUSYHB3rXsZkHJ/Dljbbbmumltpi3ntwWxikexia27QToPcPKboxBoTvd0MXJua9NPCINfDCloHgty0SGqr5I5SRd/tvEW5YQkAIMS3AXqNUDqLZjkbHj6loTwXd+xGkkPuBNvTmT30FMeW8zA0VW5C4r7Q== rsa-key-20210215"
  dannyws:
    username: "dannyws"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvr8a/Cw5eeTaP2mdn8AxqWxDsCvRFLaXHNr9MvKHwUHrA8MTRvKsrdv6wvcMxA4Qi+twDi+Q4zba99qkw4E6THiti1Y6HZCFA5uity0fRuzrLocnN+Iu+p9P1MhWCj8GWIvus4b2AZ74/nPmOA70HAy6bst0n/oD83FvIlpj89oqXhdQA3rjf2CsU2Wysx93Dd9Ti7Ki6EW9BICwUVwMtXe6+ejM/qPRURvhK1vKp9HRDz3lCcDh3/ieKlo1K3uFHgC8iTsfc6nm2EC7deXl4biIHFxZqZD4praBbT+RwiFkw/zDtORvcjxNsTU10sBDQBR+qw7m6WpFlowv44erKw== rsa-key-20210602"
