---

vhosts:
  admin.terrashift.net:
    php_fpm: "php8.1"
    doc_root: "public/"
  grafana.terrashift.net:
    proxy:
      port: 3000
  map.terrashift.net:
    proxy:
      port: 8100
      ip: "{{ ansible_ssh_host }}"
