---

- name: add daily activity cron
  cron:
    name: "activity report"
    job: "cd /home/automation/scripts/minecraft-discord-player-report/ && ./activity-check.py"
    minute: "0"
    hour: "12"
    state: present

- name: add daily creative restore
  cron:
    name: "creative restore"
    job: "/home/automation/scripts/restore-creative.sh"
    minute: "0"
    hour: "1"
    state: present

- name: add daily name updater
  cron:
    name: "MC name update"
    job: "/home/automation/scripts/whitelist-name-updater.sh"
    minute: "0"
    hour: "1"
    state: absent

- name: add whitelist sync
  cron:
    name: "whitelist sync"
    job: "/home/automation/scripts/sync-whitelist.sh"
    minute: "*/15"
    state: present

- name: rebuild main site
  cron:
    name: "rebuild main site"
    job: "/home/automation/scripts/rebuild-www.sh"
    minute: "*/10"
    state: present
