---

- name: KVM Hypervisor provisioning playbook
  hosts: hypervisors
  roles:
    - { role: common }
    - { role: hypervisor }
    - { role: docker_host }
    - { role: mariadb_server }
    - { role: webserver }
    - { role: pterodactyl_panel }
