---

- name: MC provisioning playbook
  hosts: all
  become: true
  roles:
    - {role: common, tags: common}
    - {role: docker_host, tags: docker}

- name: Include primary playbook
  import_playbook: primary.yml

- name: Include secondary playbook
  import_playbook: secondary.yml
