---

- name: MC provisioning playbook
  hosts: all
  become: true
  roles:
    - {role: common, tags: common}
    - {role: docker_host, tags: docker}
    - {role: mariadb_server, tags: [db]}
    - {role: certbot, tags: [web, certbot]}
    - {role: webserver, tags: [web]}
    - {role: pterodactyl_panel, tags: [pterodactyl]}
    - {role: wings, tags: [pterodactyl]}
    - {role: monitoring, tags: [ monitoring]}
    - {role: automation, tags: [automation]}
    - {role: stats, tags: [stats]}
    - {role: recruiting, tags: [recruiting]}
    - {role: ts-bot, tags: [ts-bot]}
