---

version: '3'

services:
  limesurvey:
    image: acspri/limesurvey
    ports:
      - 8082:80
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
    env_file:
      - .env
  mysql:
    image: mariadb
    env_file:
      - .env
