# General section controls overall behavior
[general]

    # Change the defaults here if you like, can be omitted
    libvirt_connection = qemu:///system
    libvirt_dhcp_lease_file = /var/lib/libvirt/dnsmasq/virbr1.status

    # Note: you may also use something like:
    # libvirt_connection = qemu+ssh://root@hypervisor/system
    # libvirt_dhcp_lease_file = root@hypervisor:/var/lib/libvirt/dnsmasq/virbr0.status


# All other sections are either for groups or hosts


# The default group for all identified hosts is "libvirt_guests", it will be
# created automatically but you can define vars to apply to it
[group_libvirt_guests]

    # You can define normal ansible variables for groups
    ansible_ssh_private_key_file = files/ansible


# You can define groups yourself by creating a section for them
[group_minecraft_hosts]

    # And add hosts to them, even supporting glob-style patterns
    add_hosts = mc*

[group_vms]
    add_hosts = vm*
