---

- name: Install hypervisor packages
  apt:
    pkg:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virtinst
      - libvirt-daemon
      - libguestfs-tools
      - python3-libvirt
      - python3-lxml
      - cloud-image-utils
    state: latest

- name: Create the new {{ vm_net }} network
  community.libvirt.virt_net:
    command: define
    name: "{{ vm_net }}"
    xml: '{{ lookup("template", "network-config.xml.j2") }}'

- name: Start {{ vm_net }} network
  community.libvirt.virt_net:
    command: create
    name: "{{ vm_net }}"

- name: make {{ vm_net }} network persistent over reboots
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ vm_net }}"

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Provision VMs
  include_tasks: provision.yml
  with_dict: "{{ vms }}"

- name: Ensure VMs are autostarted
  community.libvirt.virt:
    name: "{{ item.key }}"
    autostart: true
  with_dict: "{{ vms }}"

- name: Get network information after provisioning
  community.libvirt.virt_net:
    command: info
    name: "{{ vm_net }}"
  register: vm_info

- name: Persist DHCP reservations
  include_tasks: dhcp.yml
  with_dict: "{{ vms }}"

- name: Ensure temporary file is deleted
  file:
    path: "/tmp/{{ base_image_name }}"
    state: absent
  when: cleanup_tmp | bool
