---

- name: create node service
  template:
    src: "files/recruiting/node-apply.service"
    dest: "/etc/systemd/system/node-apply.service"

- name: start node service
  systemd:
    state: started
    enabled: true
    name: node-apply
    daemon_reload: true

- name: create recruitbot service
  template:
    src: "files/recruiting/recruitbot.service"
    dest: "/etc/systemd/system/recruitbot.service"

- name: start recruitbot service
  systemd:
    state: started
    enabled: true
    name: recruitbot
    daemon_reload: true

- name: create cms service
  template:
    src: "files/recruiting/cms.service"
    dest: "/etc/systemd/system/cms.service"

- name: start cms service
  systemd:
    state: started
    enabled: true
    name: cms
    daemon_reload: true
