---

- name: ensure mariadb is installed
  apt:
    pkg:
      - mariadb-server
      - python3-pymysql

- name: change root credentials
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    name: root
    host: "{{ item }}"
    password: "{{ mysql_pass }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: create root .my.cnf
  template:
    src: my.cnf.client.j2
    dest: /root/.my.cnf
    mode: "0600"
