---

- name: create node service
  template:
    src: "files/recruiting/node-locations.service"
    dest: "/etc/systemd/system/node-locations.service"

- name: start node service
  systemd:
    state: stopped
    enabled: true
    name: node-locations
    daemon_reload: true
