# This minimal config scrape only single log file.
# Primarily used in rpm/deb packaging where promtail service can be started during system init process.
# And too much scraping during init process can overload the complete system.
# https://github.com/grafana/loki/issues/11398

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: pterodactyl
    static_configs:
      - targets:
          - localhost
        labels:
          job: pterodactyl
          __path__: /var/log/pterodactyl/wings.log

  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/*-access-json.log
    pipeline_stages:
      - json:
          expressions:
            time:
            host:
            remote_ip:
            request:
            status:
            method:
            bytes:
            referrer:
            agent:
      - labels:
          host:

  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /var/log/nginx/*-error.log
