---

allowed_ports:
  - "80"
  - "443"
  - "25565"
limited_ports:
  - "22"

mysql_pass: "{{ vault_mysql_pass }}"

host_mode: "host-model"

vms:
  mc01.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
    ip_addr: 10.30.0.2
  mc02.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
    ip_addr: 10.30.0.3
  vm01.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
    ip_addr: 10.30.0.4
  vm02.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
    ip_addr: 10.30.0.5
  vm03.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
    ip_addr: 10.30.0.6

vhosts:
  admin.terrashift.net:
    php_fpm: "php8.1"
    doc_root: "public/"

pterodactyl_db: "{{ vault_pterodactyl_db }}"
pterodactyl_name: "admin.terrashift.net"
pterodactyl_mail: "{{ vault_pterodactyl_mail }}"
pterodactyl_user: "{{ vault_pterodactyl_user }}"
