---

allowed_ports:
  - "80"
  - "443"
  - "25565"
limited_ports:
  - "22"

mysql_pass: "{{ vault_mysql_pass }}"

host_mode: "host-model"

vms:
  mc01.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
  mc02.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
  vm01.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
  vm02.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
  vm03.terrashift.net:
    vcpus: 1
    ram_mb: 1024
    disk_size: 5
