---

allowed_ports:
  - "80"
  - "443"
  - "25565"
limited_ports:
  - "22"

mysql_pass: "{{ vault_mysql_pass }}"

host_mode: "host-model"

vms:
  minecraft:
    vcpus: 2
    ram_mb: 1024
    disk_size: 80
