---

- name: install java
  apt:
    pkg:
      - openjdk-17-jre
    state: present

- name: add stat update cron
  cron:
    name: "state update cron"
    job: "java -jar /home/www/stats.terrashift.net/MinecraftStatsCLI.jar /home/www/stats.terrashift.net/config.json"
    minute: "*/5"
    state: present

- name: helper script
  cron: 
    name: "bot filtering for stats"
    job: "node /home/www/stats.terrashift.net/helper/index.js"
    minute: "0"
    hour: "0"
    state: present
    
