---

- name: install ufw firewall
  apt:
    pkg:
      - ufw

- name: allow publicly accessible ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    interface: "{{ ansible_default_ipv4.interface }}"
    direction: in
  with_items:
    - "{{ allowed_ports }}"

- name: allow limited accessible ports
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
    interface: "{{ ansible_default_ipv4.interface }}"
    direction: in
  with_items:
    - "{{ limited_ports }}"

- name: allow all private traffic
  ufw:
    rule: allow
    src: 10.2.0.0/24

- name: enable UFW and disable all other ports
  ufw:
    state: enabled
    policy: deny
