#!/bin/bash

printf "
_____                        _     _  __ _
/__   \___ _ __ _ __ __ _ ___| |__ (_)/ _| |_
  / /\/ _ \ __| __/ _ / __| _ \| | |_| __|
 / / |  __/ |  | | | (_| \__ \ | | | |  _| |_
 \/   \___|_|  |_|  \__,_|___/_| |_|_|_|  \__|

Pterodactyl admin interface:  https://admin.terrashift.net/  
Monitoring dashboard:         https://grafana.terrashift.net/

Minecraft directory:          /home/minecraft/
Tool directory:               /home/automation/
Backup directory:             /home/minecraft/backups/       
"
\n