---

- name: ensure nginx is installed
  apt:
    pkg: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started

- name: create custom nginx logging config
  copy:
    src: files/nginx/000-logging.conf
    dest: /etc/nginx/conf.d/000-logging.conf
    owner: root
    group: root
    mode: 0644

- name: remove default nginx vhost
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Restart nginx

- name: create webroot directory
  file:
    path: /home/www/
    state: directory
    mode: '0755'

- name: Deploy sites
  include_tasks: vhost.yml
  with_dict: "{{ vhosts }}"
