---

- name: Setup {{ item.key }} http vhost
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.key }}.conf"
    mode: 0644

- name: Setup {{ item.key }} document root
  file:
    path: "/home/www/{{ item.key }}/{{ item.value.doc_root if item.value.doc_root is defined else '' }}"
    state: directory
    mode: 0755

- name: Enable {{ item.key }} vhost
  file:
    src: "/etc/nginx/sites-available/{{ item.key }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.conf"
    state: link
  notify:
    - Restart nginx
