---

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Restart grafana
  service:
    name: grafana-server
    state: restarted

- name: Restart promtail
  service:
    name: promtail
    state: restarted
