---

- name: import sury apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: enable php sury repo
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    filename: php-sury

- name: install php packages
  apt:
    pkg:
      - php8.3
      - php8.3-cli
      - php8.3-gd
      - php8.3-mysql
      - php8.3-mbstring
      - php8.3-bcmath
      - php8.3-xml
      - php8.3-fpm
      - php8.3-curl
      - php8.3-zip
      - php8.3-intl
      - php8.3-redis
      - redis-server
      - composer
    state: present

- name: create mariadb database
  mysql_db:
    name: "{{ pterodactyl_db.database }}"
    state: present

- name: create pterodactyl db user
  mysql_user:
    login_host: 127.0.0.1
    login_port: 3306
    name: "{{ pterodactyl_db.username }}"
    password: "{{ pterodactyl_db.password }}"
    priv: "{{ pterodactyl_db.database }}.*:ALL"
    state: present

- name: Check if we are doing the initial install
  find:
    paths: "/home/www/{{ pterodactyl_name }}/public/"
  register: initial_setup

- name: Initial pterodactyl setup
  include_tasks: install.yml
  when: initial_setup.matched == 0
