---

name: "Ansible"

on:
  push:
    branches:
      - main

jobs:
  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Detect tag usage
        run: |
          echo "TAGS=all" >> "$GITHUB_ENV"
          commit_msg=$(git log -1 --no-merges --pretty=%B)
          if [[ $commit_msg =~ ^\[(.*)\].* ]]; then
            echo "TAGS=${BASH_REMATCH[1]}" >> "$GITHUB_ENV"
          fi
          echo "$TAGS"

      - name: Run ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASS }}
          options: |
            --tags ${{ env.TAGS }}
